---
title: 'DATA607 - Assignment #3'
author: "Sang Yoon (Andy) Hwang"
date: "February 15, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#3-1

```{r 3-1}
#3-1
library(stringr)
raw.data <- "555-1239Moe Szyslak(636) 555-0113Burns, C. Montgomery555
-6542Rev. Timothy Lovejoy555 8904Ned Flanders636-555-3226Simpson, Homer5553642Dr. Julius Hibbert"

name <- unlist(str_extract_all(raw.data, "[[:alpha:]., ]{2,}"))
name

name1 <- ifelse(grepl( ",",name),paste(word(name,-1),word(name,1)),name)

name2 <- gsub("Rev.|Dr.|,","",name1)

name2 <- trimws(name2)

name2

```

##3-2

```{r 3-2}
#3-2
name

name_title_detect <- str_detect(name, "Rev.|Dr.")

name_title <- data.frame(cbind(name, name_title_detect))

name_title
```

##3-3

```{r 3-3}
#3-3
grepl(" ", name2)
```

##4-1

```{r 4-1}
#4-1
a <- c('1$','$2','33.345$','35555553$')
grep("[0-9]+\\$",a)
str_extract(a,"[0-9]+\\$")

#One or more digits start with 0 to 9 and ends with $
```

##4-2

```{r 4-2}
#4-2
a <- c("ea", "f", "ea1", "abcd", "abc", "Aade", "aaaaaaaaaa")
grep("\\b[a-z]{1,4}\\b",a)
str_extract(a, "\\b[a-z]{1,4}\\b")

## string boundary 1 to 4 lower case English character only from A to Z
```

##4-3

```{r 4-3}
## 4-3
a <- c("a.txt", "a.txt$", "atxt", "1.txt", ".txt", ".d.txt")
grep(".*?\\.txt$",a)
str_extract(a, ".*?\\.txt$")

## find all matches of 0 or more number of string and numeric characters that end with .txt
```

##4-4

```{r 4-4}
## 4-4
a <- c("01/10/2017", "01/11/222", "11-11-1111")
grep("\\d{2}/\\d{2}/\\d{4}",a)
str_extract(a,"\\d{2}/\\d{2}/\\d{4}")

## find 2 digits / 2 digits / 4 digits
```

##4-5

```{r 4-5}
### 4-5
a <- c("<html>de35</html>", "<html>?<html>", "<d></d>", "<d>ggds</e>", "<44>?</44>")
grep("<(.+?)>.+?</\\1>",a)
str_extract(a, "<(.+?)>.+?</\\1>")

##<1st pattern> at least 1 character </following 1st pattern match>
```

##9

```{r 9}
### 9
raw.data<-"clcopCow1zmstc0d87wnkig7OvdicpNuggvhryn92Gjuwczi8hqrfpRxs5Aj5dwpn0Tanwo
Uwisdij7Lj8kpf03AT5Idr3coc0bt7yczjatOaootj55t3Nj3ne6c4Sfek.r1w1YwwojigO
d6vrfUrbz2.2bkAnbhzgv4R9i05zEcrop.wAgnb.SqoU65fPa1otfb7wEm24k6t3sR9zqe5
fy89n6Nd5t9kc4fE905gmc4Rgxo5nhDk!gr"

a <-unlist(str_extract_all(raw.data, "[:upper:]"))
a
```